Lambda Function in Python

In [1]:
def sqr(y):
    return y**2

In [2]:
s = lambda y: y**2

In [3]:
print(s(7))

49

In [4]:
print((sqr(7)))

49

In [5]:
s2 = lambda x,y:x*y

In [6]:
x = 4
y = 5

In [7]:
print(s2(4,5))

20

In [8]:
import pandas as pd

In [9]:
file ='C:/R/Data/loans data.csv'

In [10]:
pd = pd.read_csv(file)

In [11]:
pd

,ID,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
0,81174.0,20000,20000,8.90%,36 months,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14,14272,2.0,< 1 year
1,99592.0,19200,19200,12.12%,36 months,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12,11140,1.0,2 years
2,80059.0,35000,35000,21.98%,60 months,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14,21977,1.0,2 years
3,15825.0,10000,9975,9.99%,36 months,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10,9346,0.0,5 years
4,33182.0,12000,12000,11.71%,36 months,credit_card,18.78%,NJ,RENT,3195.00,695-699,11,14469,0.0,9 years
5,62403.0,6000,6000,15.31%,36 months,other,20.05%,CT,OWN,4891.67,670-674,17,10391,2.0,3 years
6,48808.0,10000,10000,7.90%,36 months,debt_consolidation,26.09%,MA,RENT,2916.67,720-724,10,15957,0.0,10+ years
7,22090.0,33500,33450,17.14%,60 months,credit_card,14.70%,LA,MORTGAGE,13863.42,705-709,12,27874,0.0,10+ years
8,76404.0,14675,14675,14.33%,36 months,credit_card,26.92%,CA,RENT,3150.00,685-689,9,7246,1.0,8 years
9,15867.0,.,7000,6.91%,36 months,credit_card,7.10%,CA,RENT,5000.00,715-719,8,7612,0.0,3 years
10,94971.0,2000,2000,19.72%,36 months,moving,10.29%,FL,RENT,3575.00,670-674,10,12036,0.0,6 years
11,36911.0,10625,10625,14.27%,36 months,debt_consolidation,12.54%,CA,MORTGAGE,4250.00,665-669,14,10767,0.0,< 1 year
12,41200.0,28000,27975,21.67%,60 months,debt_consolidation,13.07%,CT,MORTGAGE,14166.67,670-674,12,10311,0.0,1 year
13,83869.0,35000,34950,8.90%,36 months,debt_consolidation,20.46%,CT,RENT,9166.67,735-739,19,21536,0.0,1 year
14,53853.0,9600,9600,7.62%,36 months,debt_consolidation,3.45%,DC,RENT,11250.00,725-729,13,4606,0.0,< 1 year
15,21399.0,25000,24975,15.65%,60 months,debt_consolidation,21.99%,CA,RENT,5416.67,730-734,6,13929,0.0,9 years
16,62127.0,10000,10000,12.12%,36 months,debt_consolidation,17.72%,CA,RENT,9000.00,695-699,18,20317,0.0,7 years
17,23446.0,14000,13900.25,10.37%,60 months,debt_consolidation,11.95%,OH,RENT,4333.33,740-744,6,7419,0.0,9 years
18,44987.0,10000,10000,9.76%,36 months,credit_card,7.13%,FL,RENT,2733.33,730-734,7,6112,2.0,3 years
19,17977.0,5200,5175,9.99%,60 months,debt_consolidation,10.29%,AL,MORTGAGE,3750.00,760-764,10,16094,0.0,.
20,86099.0,22000,21975,21.98%,36 months,debt_consolidation,11.19%,TX,MORTGAGE,6666.67,665-669,9,23124,0.0,10+ years
21,99483.0,30000,30000,19.05%,60 months,credit_card,21.25%,FL,MORTGAGE,6250.00,695-699,12,34927,0.0,6 years
22,28798.0,6500,6500,17.99%,60 months,car,19.63%,FL,RENT,4100.00,665-669,11,11697,1.0,2 years
23,24168.0,17400,17400,11.99%,36 months,credit_card,12.47%,AZ,RENT,6833.33,695-699,7,26587,0.0,7 years
24,10356.0,4000,4000,16.82%,60 months,vacation,13.71%,GA,MORTGAGE,4500.00,670-674,5,20804,0.0,3 years
25,46027.0,7200,7200,7.90%,36 months,debt_consolidation,24.82%,TX,RENT,5416.67,705-709,8,12017,0.0,7 years
26,2238.0,8000,8000,14.42%,36 months,debt_consolidation,24.63%,MA,RENT,2964.17,675-679,9,8928,2.0,6 years
27,65278.0,8000,8000,15.31%,36 months,debt_consolidation,15.46%,CA,MORTGAGE,2916.67,675-679,.,7152,1.0,5 years
28,4227.0,3000,.,8.59%,36 months,other,3.72%,MA,MORTGAGE,4167.00,765-769,4,7074,0.0,5 years
29,50182.0,14500,14500,7.90%,36 months,debt_consolidation,4.85%,GA,MORTGAGE,3958.33,760-764,4,9598,0.0,4 years
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2470,84265.0,20000,20000,22.95%,60 months,debt_consolidation,7.10%,NJ,RENT,6750.00,665-669,6,16104,1.0,7 years
2471,80231.0,19000,19000,7.90%,36 months,debt_consolidation,9.76%,RI,MORTGAGE,5166.67,770-774,18,43617,2.0,10+ years
2472,49533.0,17300,17250,22.45%,60 months,wedding,3.58%,PA,MORTGAGE,5500.00,685-689,11,2306,3.0,4 years
2473,102514.0,7000,711.54,15.13%,36 months,major_purchase,18.91%,CO,MORTGAGE,3833.00,650-654,13,12634,0.0,2 years
2474,78618.0,7200,7200,18.75%,36 months,debt_consolidation,16.21%,MI,RENT,8333.33,660-664,8,28916,0.0,10+ years
2475,86953.0,10000,10000,14.09%,36 months,major_purchase,9.71%,CO,RENT,4583.33,675-679,6,3859,0.0,< 1 year
2476,80129.0,4000,3925,14.09%,36 months,credit_card,12.27%,FL,MORTGAGE,8583.33,675-679,9,36943,1.0,10+ years
2477,85216.0,17500,17500,8.90%,36 months,debt_consolidation,10.94%,UT,MORTGAGE,25000.00,730-734,9,34545,0.0,6 years
2478,38247.0,20000,20000,11.71%,36 months,credit_card,9.58%,SD,MORTGAGE,5416.67,725-729,12,18267,1.0,4 years
2479,91245.0,16200,16200,15.80%,60 months,debt_consolidation,7.92%,PA,MORTGAGE,4833.33,680-684,12,12313,2.0,10+ years
2480,53041.0,10000,10000,6.03%,36 months,small_business,13.03%,FL,RENT,5000.00,760-764,8,3952,0.0,2 years
2481,63051.0,27000,27000,6.62%,36 months,debt_consolidation,12.21%,OH,MORTGAGE,9250.00,810-814,12,4211,0.0,5 years
2482,14446.0,4500,4475,7.51%,36 months,small_business,20.27%,VA,MORTGAGE,7075.50,720-724,15,68618,2.0,10+ years
2483,68628.0,.,15875,14.33%,36 months,small_business,17.44%,MD,MORTGAGE,3416.67,675-679,11,15891,0.0,2 years
2484,98758.0,15000,15000,10.16%,36 months,credit_card,28.28%,OH,MORTGAGE,6666.67,690-694,15,14880,0.0,10+ years
2485,13070.0,25000,24950,10.75%,36 months,debt_consolidation,20.48%,OR,MORTGAGE,7083.33,765-769,10,25429,0.0,6 years
2486,45836.0,7000,7000,17.27%,36 months,other,18.38%,NY,OWN,2464.37,665-669,9,7089,0.0,3 years
2487,52330.0,15000,15000,19.99%,36 months,wedding,18.05%,CA,RENT,8000.00,660-664,6,45976,1.0,2 years
2488,48243.0,17000,17000,15.81%,36 months,debt_consolidation,17.01%,CO,RENT,3833.33,685-689,6,15484,1.0,6 years
2489,63256.0,19075,19075,18.75%,36 months,debt_consolidation,15.23%,NY,RENT,5166.67,670-674,17,13749,3.0,10+ years
2490,42124.0,10000,10000,11.71%,36 months,debt_consolidation,8.40%,CA,RENT,4500.00,710-714,8,8404,1.0,3 years
2491,78043.0,8475,8475,7.62%,36 months,debt_consolidation,15.88%,CA,RENT,3983.33,720-724,9,6882,0.0,NaN
2492,925.0,6400,6350,10.08%,36 months,debt_consolidation,8.11%,NJ,MORTGAGE,5166.67,710-714,5,5815,2.0,10+ years
2493,74047.0,30000,30000,23.28%,60 months,other,12.10%,IL,MORTGAGE,7083.33,675-679,16,17969,1.0,10+ years
2494,49957.0,24000,23975,14.65%,36 months,debt_consolidation,15.29%,WA,MORTGAGE,6666.67,685-689,13,17521,0.0,5 years
2495,23735.0,30000,29950,16.77%,60 months,debt_consolidation,19.23%,NY,MORTGAGE,9250.00,705-709,15,45880,1.0,8 years
2496,65882.0,16000,16000,14.09%,60 months,home_improvement,21.54%,MD,OWN,8903.25,740-744,18,18898,1.0,10+ years
2497,55610.0,10000,10000,13.99%,36 months,debt_consolidation,4.89%,PA,MORTGAGE,2166.67,680-684,4,4544,0.0,10+ years
2498,38576.0,6000,6000,12.42%,36 months,major_purchase,16.66%,NJ,RENT,3500.00,675-679,8,.,0.0,5 years
2499,3116.0,9000,5242.75,13.79%,36 months,debt_consolidation,6.76%,NY,RENT,3875.00,670-674,7,7589,0.0,10+ years

In [12]:
pd['new_col'] = pd['Interest.Rate'].apply (lambda x: x[:-1])

In [13]:
pd['yearly_income'] = pd['Monthly.Income'].apply (lambda x: [x*12])

In [14]:
pd['yearly_income'].head()

0    [78500.04000000001]
1             [54999.96]
2             [138000.0]
3             [45999.96]
4              [38340.0]
Name: yearly_income, dtype: object

##map function in Python

In [15]:
items = [1,2,3]
squared =[]
for x in items:
    squared.append(x**2)

In [16]:
squared

[1, 4, 9]

In [17]:
def sqr(y):
    return y**2
list(map(sqr,items))

[1, 4, 9]

In [18]:
import numpy as np
import time
items = np.random.rand(1,100,1000)
a= time.time()
squared = []
for x in items:
    squared.append(x**2)
b= time.time()
run1= b-a
print(run1)

0.0010297298431396484

In [19]:
a= time.time()
def sqr(y):
    return y**2
list(map(sqr,items))
b=time.time()
run2=b-a
print(run2)

0.001001596450805664

In [20]:
(run1-run2)/run1*100

2.7321139152581617

In [21]:
items = [1,2,3]
list(map(lambda x:x**2, items))

[1, 4, 9]

In [22]:
ls= list(range(-5,5))

In [23]:
ls

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]

In [24]:
def select_positive(x):
    if x>0:
        return True

In [25]:
positive=[]
for i in ls:
    if select_positive(i):
        positive.append(i)
print(positive)

[1, 2, 3, 4]

In [26]:
list(filter(select_positive, ls))

[1, 2, 3, 4]

In [27]:
list(filter((lambda x:x>0), ls))

[1, 2, 3, 4]

##Reduce Function

In [29]:
from functools import reduce

In [38]:
ls = [1,2,4,5]
reduce((lambda x,y:x+y),ls)

12

In [47]:
ls = [1,2,4,5]
reduce(lambda x,y:max(x,y),ls)

5

## List Comprehension

In [48]:
x = [i for i in range(10)]
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
squares = []
for x in range(10):
    squares = [x**2 for x in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [55]:
new_lst = ["M","A","Y","A","N","K"]

In [57]:
lower=[x.lower() for x in new_lst]
print(lower)

['m', 'a', 'y', 'a', 'n', 'k']

In [58]:
new_lst2 = ["S", "H", "A", "R", "M", "A"]

In [74]:
s= "."
jn= s.join(new_lst2)
print(jn)

S.H.A.R.M.A

In [100]:
new_lst3 = [2,4,5,6,7,8]

In [106]:
even_squares =[]
for num in new_lst3: 
      if num % 2 == 0:
        even_squares.append(num**2)
print(even_squares)

[4, 16, 36, 64]

In [141]:
# myDict = {} 
myDict = {"Jan":31, "Feb":28, "March":31, "April":30, "May":31, "June":30, "July":31, "August":31, "Sep":30, "Oct":31, "Nov":30, "Dec":31}
print(myDict)

{'Jan': 31, 'Feb': 28, 'March': 31, 'April': 30, 'May': 31, 'June': 30, 'July': 31, 'August': 31, 'Sep': 30, 'Oct': 31, 'Nov': 30, 'Dec': 31}

In [142]:
for i in myDict: 
    if myDict.Value>30:
print(myDict.Key)

IndentationError: expected an indented block (<ipython-input-142-c7f7ec15352c>, line 3)